/* Lab Question  (Test 2)
 * 
 * A bottom-up approach is typically used in OOP languages. This is the general design approach that has been used
 * for this software. Do you think it would have been easier or harder to approach this project using a top-down approach?
 * Why do you think a bottom up approach is generally more natural when using OOP languages?
 *
 */

using System;
using System.Collections.Generic;

using Psim.ModelComponents;
using Psim.Materials;

namespace Psim
{
	// Model is comprised of a single material. Hardcoding the time step & number of phonons for now.
	class Model
	{
		private const double TIME_STEP = 5e-12;
		private const int NUM_PHONONS = 10000000;
		private Material material;
		private List<Cell> cells = new() { };
		private List<Sensor> sensors = new() { };
		private readonly double highTemp;
		private readonly double lowTemp;
		private readonly double simTime;
		private readonly double tEq;

		public Model(Material material, double highTemp, double lowTemp, double simTime)
		{
			this.material = material;
			this.highTemp = highTemp;
			this.lowTemp = lowTemp;
			this.simTime = simTime;
			tEq = (highTemp + lowTemp) / 2;
		}

		// TODO: Write a method to add a sensor to the model
		// TODO: Write a method to add a cell to the model
		public void AddSensor(int SensorID, double intiTemp)
        {

        }

		public void AddSensor(double initTemp)
        {

        }

		public void AddCell(double length, double width, int SensorID)
        {

        }
		/// <summary>
		/// Automatically sets all the surfaces in the cells that constitute this model.
		/// Should be called after all the cells have been added
		/// </summary>
		/// <param name="tEq">The equilibrium temperature of the system</param>
		private void SetSurfaces(double tEq)
		{
			// TODO: Implemenent -> Assume that the system is linear!!
			int numCells = cells.Count;
			if (numCells < 2)
			{
				// throw custom exception
			}
			// Continue with implementation
			throw new NotImplementedException();
		}

		/// <summary>
		/// Calibrates the emitting surfaces in the model.
		/// </summary>
		/// <param name="tEq">System equilibrium temperature</param>
		/// <param name="effEnergy">Phonon packet effective energy</param>
		/// <param name="timeStep">Simulation time step</param>
		private void SetEmitPhonons(double tEq, double effEnergy, double timeStep)
		{
			// TODO: Implement -> just need to call the appropriate method in each cell
			throw new NotImplementedException();
		}

		/// <summary>
		/// Returns the total energy of the model (initial energy + emit energy)
		/// </summary>
		/// <returns>Total energy generated by the model over the course of the simulation</returns>
		private double GetTotalEnergy()
		{
			// TODO: Implement -> just need to call the appropriate method in each cell
			throw new NotImplementedException();
		}
	}
}
